Pr치ctica 3 de PAV - detecci칩n de pitch: upc::FileInfo Class Reference
upc::FileInfo Class Reference
#include "filename.h"
Public Types
enum ftype { ERR, DIR, REG }
Public Member Functions
FileInfo (ftype tp, long long size)
ftype type () const
long long size () const
Private Attributes
ftype _type
long long _size
Detailed Description
Definition at line 40 of file filename.h.
Member Enumeration Documentation
ftype
enum upc::FileInfo::ftype
Enumerator
ERR
DIR
REG
Definition at line 42 of file filename.h.
Constructor & Destructor Documentation
FileInfo()
upc::FileInfo::FileInfo (ftype tp, long long size) inline
Definition at line 43 of file filename.h.
Member Function Documentation
size()
long long upc::FileInfo::size () const inline
Definition at line 45 of file filename.h.
Referenced by upc::Filename::size().
type()
ftype upc::FileInfo::type () const inline
Definition at line 44 of file filename.h.
Referenced by upc::Directory::exist(), and upc::Filename::exist().
Member Data Documentation
_size
long long upc::FileInfo::_size private
Definition at line 48 of file filename.h.
_type
ftype upc::FileInfo::_type private
Definition at line 47 of file filename.h.
The documentation for this class was generated from the following file:
/Users/davidbonet/Desktop/p3-priv/src/include/filename.h