Pr치ctica 3 de PAV - detecci칩n de pitch: docopt::Option Class Reference
docopt::Option Class Reference final
#include "docopt_private.h"
Public Member Functions
Option (std::string shortOption, std::string longOption, int argcount=0, value v=value{false})
Option (Option const &)=default
Option (Option &&)=default
Option & operator= (Option const &)=default
Option & operator= (Option &&)=default
std::string const & longOption () const
std::string const & shortOption () const
int argCount () const
virtual size_t hash () const override
void setValue (value &&v)
Public Member Functions inherited from docopt::LeafPattern
LeafPattern (std::string name, value v={})
virtual std::vector< Pattern * > flat (bool(*filter)(Pattern const *)) override
virtual void collect_leaves (std::vector< LeafPattern * > &lst) override final
virtual bool match (PatternList &left, std::vector< std::shared_ptr< LeafPattern >> &collected) const override
virtual bool hasValue () const override
value const & getValue () const
void setValue (value &&v)
virtual std::string const & name () const override
Public Member Functions inherited from docopt::Pattern
std::vector< LeafPattern * > leaves ()
virtual ~Pattern ()=default
Static Public Member Functions
static Option parse (std::string const &option_description)
Protected Member Functions
virtual std::pair< size_t, std::shared_ptr< LeafPattern > > single_match (PatternList const &left) const override
Private Attributes
std::string fShortOption
std::string fLongOption
int fArgcount
Detailed Description
Definition at line 237 of file docopt_private.h.
Constructor & Destructor Documentation
Option() [1/3]
docopt::Option::Option (std::string shortOption, std::string longOption, int argcount = 0, value v = value{false}) inline
Definition at line 243 of file docopt_private.h.
Option() [2/3]
docopt::Option::Option (Option const &) default
Option() [3/3]
docopt::Option::Option (Option &&) default
Member Function Documentation
argCount()
int docopt::Option::argCount () const inline
Definition at line 269 of file docopt_private.h.
References fArgcount.
hash()
virtual size_t docopt::Option::hash () const inline override virtual
Reimplemented from docopt::LeafPattern.
Definition at line 271 of file docopt_private.h.
References fArgcount, fLongOption, fShortOption, docopt::LeafPattern::hash(), and docopt::hash_combine().
longOption()
std::string const& docopt::Option::longOption () const inline
Definition at line 267 of file docopt_private.h.
References fLongOption.
Referenced by parse().
operator=() [1/2]
Option& docopt::Option::operator= (Option &&) default
operator=() [2/2]
Option& docopt::Option::operator= (Option const &) default
parse()
Option docopt::Option::parse (std::string const & option_description) inline static
Definition at line 523 of file docopt_private.h.
References longOption(), docopt::LeafPattern::match(), and shortOption().
Referenced by parse_defaults().
setValue()
void docopt::LeafPattern::setValue inline
Definition at line 121 of file docopt_private.h.
shortOption()
std::string const& docopt::Option::shortOption () const inline
Definition at line 268 of file docopt_private.h.
References fShortOption.
Referenced by parse().
single_match()
std::pair< size_t, std::shared_ptr< LeafPattern > > docopt::Option::single_match (PatternList const & left) const inline override protected virtual
Implements docopt::LeafPattern.
Definition at line 579 of file docopt_private.h.
Member Data Documentation
fArgcount
int docopt::Option::fArgcount private
Definition at line 285 of file docopt_private.h.
Referenced by argCount(), and hash().
fLongOption
std::string docopt::Option::fLongOption private
Definition at line 284 of file docopt_private.h.
Referenced by hash(), and longOption().
fShortOption
std::string docopt::Option::fShortOption private
Definition at line 283 of file docopt_private.h.
Referenced by hash(), and shortOption().
The documentation for this class was generated from the following file:
/Users/davidbonet/Desktop/p3-priv/src/pav/docopt_cpp/docopt_private.h