Pr치ctica 3 de PAV - detecci칩n de pitch: docopt::LeafPattern Class Reference
docopt::LeafPattern Class Reference abstract
#include "docopt_private.h"
Public Member Functions
LeafPattern (std::string name, value v={})
virtual std::vector< Pattern * > flat (bool(*filter)(Pattern const *)) override
virtual void collect_leaves (std::vector< LeafPattern * > &lst) override final
virtual bool match (PatternList &left, std::vector< std::shared_ptr< LeafPattern >> &collected) const override
virtual bool hasValue () const override
value const & getValue () const
void setValue (value &&v)
virtual std::string const & name () const override
virtual size_t hash () const override
Public Member Functions inherited from docopt::Pattern
std::vector< LeafPattern * > leaves ()
virtual ~Pattern ()=default
Protected Member Functions
virtual std::pair< size_t, std::shared_ptr< LeafPattern > > single_match (PatternList const &) const =0
Private Attributes
std::string fName
value fValue
Detailed Description
Definition at line 97 of file docopt_private.h.
Constructor & Destructor Documentation
LeafPattern()
docopt::LeafPattern::LeafPattern (std::string name, value v = {}) inline
Definition at line 100 of file docopt_private.h.
Member Function Documentation
collect_leaves()
virtual void docopt::LeafPattern::collect_leaves (std::vector< LeafPattern * > & lst) inline final override virtual
Implements docopt::Pattern.
Definition at line 112 of file docopt_private.h.
flat()
virtual std::vector<Pattern*> docopt::LeafPattern::flat (bool(*)(Pattern const *) filter) inline override virtual
Implements docopt::Pattern.
Definition at line 105 of file docopt_private.h.
getValue()
value const& docopt::LeafPattern::getValue () const inline
Definition at line 120 of file docopt_private.h.
References fValue.
Referenced by docopt::BranchPattern::fix_repeating_arguments(), and match().
hash()
virtual size_t docopt::LeafPattern::hash () const inline override virtual
Implements docopt::Pattern.
Reimplemented in docopt::Option.
Definition at line 125 of file docopt_private.h.
References fName, fValue, and docopt::hash_combine().
Referenced by docopt::Option::hash().
hasValue()
virtual bool docopt::LeafPattern::hasValue () const inline override virtual
Reimplemented from docopt::Pattern.
Definition at line 118 of file docopt_private.h.
References fValue.
match()
bool docopt::LeafPattern::match (PatternList & left, std::vector< std::shared_ptr< LeafPattern >> & collected) const inline override virtual
cant be!?
Implements docopt::Pattern.
Definition at line 438 of file docopt_private.h.
References getValue(), and single_match().
Referenced by docopt::Option::parse().
name()
virtual std::string const& docopt::LeafPattern::name () const inline override virtual
Implements docopt::Pattern.
Definition at line 123 of file docopt_private.h.
References fName.
Referenced by docopt::Argument::single_match(), and docopt::Command::single_match().
setValue()
void docopt::LeafPattern::setValue (value && v) inline
Definition at line 121 of file docopt_private.h.
References fValue.
Referenced by docopt::BranchPattern::fix_repeating_arguments().
single_match()
virtual std::pair<size_t, std::shared_ptr<LeafPattern> > docopt::LeafPattern::single_match (PatternList const &) const protected pure virtual
Implemented in docopt::Option, docopt::Command, and docopt::Argument.
Referenced by match().
Member Data Documentation
fName
std::string docopt::LeafPattern::fName private
Definition at line 136 of file docopt_private.h.
Referenced by hash(), and name().
fValue
value docopt::LeafPattern::fValue private
Definition at line 137 of file docopt_private.h.
Referenced by getValue(), hash(), hasValue(), and setValue().
The documentation for this class was generated from the following file:
/Users/davidbonet/Desktop/p3-priv/src/pav/docopt_cpp/docopt_private.h