Pr치ctica 3 de PAV - detecci칩n de pitch: upc::PitchAnalyzer Class Reference
upc::PitchAnalyzer Class Reference
#include "pitch_analyzer.h"
Public Types
enum Window { RECT, HAMMING }
Wndow type.
Public Member Functions
void set_window (Window type)
pre-compute window
PitchAnalyzer (unsigned int fLen, unsigned int sFreq, Window w=PitchAnalyzer::HAMMING, float min_F0=MIN_F0, float max_F0=MAX_F0)
float operator() (const std::vector< float > &_x) const
float operator() (const float *pt, unsigned int N) const
float operator() (std::vector< float >::const_iterator begin, std::vector< float >::const_iterator end) const
void set_f0_range (float min_F0, float max_F0)
Private Member Functions
void autocorrelation (const std::vector< float > &x, std::vector< float > &r) const
float compute_pitch (std::vector< float > &x) const
bool unvoiced (float pot, float r1norm, float rmaxnorm) const
Private Attributes
std::vector< float > window
precomputed window
unsigned int frameLen
length of frame (in samples). Has to be set in the constructor call
unsigned int samplingFreq
sampling rate (in samples per second). Has to be set in the constructor call
unsigned int npitch_min
minimum value of pitch period, in samples
unsigned int npitch_max
maximum value of pitch period, in samples
Detailed Description
PitchAnalyzer: class that computes the pitch (in Hz) from a signal frame. No pre-processing or post-processing has been included
Definition at line 17 of file pitch_analyzer.h.
Member Enumeration Documentation
Window
enum upc::PitchAnalyzer::Window
Wndow type.
Enumerator
RECT
Rectangular window.
HAMMING
Hamming window.
Definition at line 20 of file pitch_analyzer.h.
Constructor & Destructor Documentation
PitchAnalyzer()
upc::PitchAnalyzer::PitchAnalyzer (unsigned int fLen, unsigned int sFreq, Window w = PitchAnalyzer::HAMMING, float min_F0 = MIN_F0, float max_F0 = MAX_F0) inline
Parameters
fLen Frame length in samples
sFreq Sampling rate in Hertzs
w Window type
min_F0 Pitch range should be restricted to be above this value
max_F0 Pitch range should be restricted to be below this value
Definition at line 51 of file pitch_analyzer.h.
References frameLen, samplingFreq, set_f0_range(), and set_window().
Member Function Documentation
autocorrelation()
void upc::PitchAnalyzer::autocorrelation (const std::vector< float > & x, std::vector< float > & r) const private
Computes correlation from lag=0 to r.size()
TODO:
[TODO]:
Compute the autocorrelation r[l]
Definition at line 11 of file pitch_analyzer.cpp.
compute_pitch()
float upc::PitchAnalyzer::compute_pitch (std::vector< float > & x) const private
Returns the pitch (in Hz) of input frame x
TODO:
[TODO]:
Find the lag of the maximum value of the autocorrelation away from the origin.
Choices to set the minimum value of the lag are:
The first negative value of the autocorrelation.
The lag corresponding to the maximum value of the pitch.
In either case, the lag should not exceed that of the minimum value of the pitch.
Definition at line 56 of file pitch_analyzer.cpp.
Referenced by operator()().
operator()() [1/3]
float upc::PitchAnalyzer::operator() (const float * pt, unsigned int N) const inline
Operator (): computes the pitch for the given "C" vector (float *). N is the size of the vector pointer by pt.
copy input values into local vector x
Definition at line 79 of file pitch_analyzer.h.
References compute_pitch(), frameLen, and N.
operator()() [2/3]
float upc::PitchAnalyzer::operator() (const std::vector< float > & _x) const inline
Operator (): computes the pitch for the given vector x
Definition at line 67 of file pitch_analyzer.h.
References compute_pitch(), and frameLen.
operator()() [3/3]
float upc::PitchAnalyzer::operator() (std::vector< float >::const_iterator begin, std::vector< float >::const_iterator end) const inline
Operator (): computes the pitch for the given vector, expressed by the begin and end iterators
Definition at line 91 of file pitch_analyzer.h.
References compute_pitch(), and frameLen.
set_f0_range()
void upc::PitchAnalyzer::set_f0_range (float min_F0, float max_F0)
Sets pitch range: takes min_F0 and max_F0 in Hz, sets npitch_min and npitch_max in samples
Definition at line 37 of file pitch_analyzer.cpp.
Referenced by PitchAnalyzer().
set_window()
void upc::PitchAnalyzer::set_window (Window type)
pre-compute window
TODO:
[TODO]:
Implement the Hamming window
Definition at line 21 of file pitch_analyzer.cpp.
Referenced by PitchAnalyzer().
unvoiced()
bool upc::PitchAnalyzer::unvoiced (float pot, float r1norm, float rmaxnorm) const private
Returns true is the frame is unvoiced
TODO:
[TODO]:
Implement a rule to decide whether the sound is voiced or not.
You can use the standard features (pot, r1norm, rmaxnorm), or compute and use other ones.
Definition at line 49 of file pitch_analyzer.cpp.
Member Data Documentation
frameLen
unsigned int upc::PitchAnalyzer::frameLen private
length of frame (in samples). Has to be set in the constructor call
Definition at line 29 of file pitch_analyzer.h.
Referenced by operator()(), and PitchAnalyzer().
npitch_max
unsigned int upc::PitchAnalyzer::npitch_max private
maximum value of pitch period, in samples
Definition at line 32 of file pitch_analyzer.h.
npitch_min
unsigned int upc::PitchAnalyzer::npitch_min private
minimum value of pitch period, in samples
Definition at line 31 of file pitch_analyzer.h.
samplingFreq
unsigned int upc::PitchAnalyzer::samplingFreq private
sampling rate (in samples per second). Has to be set in the constructor call
Definition at line 30 of file pitch_analyzer.h.
Referenced by PitchAnalyzer().
window
std::vector<float> upc::PitchAnalyzer::window private
precomputed window
Definition at line 28 of file pitch_analyzer.h.
The documentation for this class was generated from the following files:
/Users/davidbonet/Desktop/p3-priv/src/get_pitch/pitch_analyzer.h
/Users/davidbonet/Desktop/p3-priv/src/get_pitch/pitch_analyzer.cpp