Pr치ctica 3 de PAV - detecci칩n de pitch: upc::Directory Class Reference
upc::Directory Class Reference
#include "filename.h"
Public Member Functions
Directory ()
Directory (const Path &p)
Directory (const string &p)
Directory (const char *p)
bool make () const
bool exist () const
virtual ~Directory ()
Public Member Functions inherited from upc::Path
Path ()
Path (const string &str)
Path (const char *str)
virtual ~Path ()
Detailed Description
Definition at line 72 of file filename.h.
Constructor & Destructor Documentation
Directory() [1/4]
upc::Directory::Directory () inline
Definition at line 74 of file filename.h.
Directory() [2/4]
upc::Directory::Directory (const Path & p) inline
Definition at line 75 of file filename.h.
Directory() [3/4]
upc::Directory::Directory (const string & p) inline
Definition at line 76 of file filename.h.
Directory() [4/4]
upc::Directory::Directory (const char * p) inline
Definition at line 77 of file filename.h.
~Directory()
virtual upc::Directory::~Directory () inline virtual
Definition at line 80 of file filename.h.
Member Function Documentation
exist()
bool upc::Directory::exist () const
Definition at line 200 of file filename.cpp.
References upc::FileInfo::DIR, upc::fileInfo(), and upc::FileInfo::type().
Referenced by upc::Filename::checkDir().
make()
bool upc::Directory::make () const
Definition at line 206 of file filename.cpp.
References MkDir().
Referenced by upc::Filename::checkDir().
The documentation for this class was generated from the following files:
/Users/davidbonet/Desktop/p3-priv/src/include/filename.h
/Users/davidbonet/Desktop/p3-priv/src/pav/filename.cpp