Pr치ctica 3 de PAV - detecci칩n de pitch: upc Namespace Reference
upc Namespace Reference
Name space of UPC.
Namespaces
ascii
Classes
class array
class CircularIndex
Circular Index used to go through state circular buffer (u)
class DigitalFilter
Digital filter implemented using direct form.
class Directory
class Ext
class FileInfo
class Filename
class KeyValue
class matrix
class Path
class PitchAnalyzer
Typedefs
typedef vector< string > vstring
typedef array< int > ivector
typedef matrix< int > imatrix
typedef array< float > fvector
typedef matrix< float > fmatrix
typedef array< double > dvector
typedef matrix< double > dmatrix
Functions
int getCols (istream &is, vstring &cols)
bool keyStroke (char key=0)
template<class _Ty >
std::ostream & operator<< (std::ostream &os, const array< _Ty > &f)
template<class _Ty >
std::istream & operator>> (std::istream &is, array< _Ty > &f)
template<class _Ty >
std::ostream & operator<< (std::ostream &os, const matrix< _Ty > &f)
template<class _Ty >
std::istream & operator>> (std::istream &is, matrix< _Ty > &f)
FileInfo fileInfo (const Path &fname)
Variables
const float MIN_F0 = 20.0F
Minimum value of pitch in Hertzs.
const float MAX_F0 = 10000.0F
Maximum value of pitch in Hertzs.
Detailed Description
Name space of UPC.
Typedef Documentation
dmatrix
typedef matrix<double> upc::dmatrix
Definition at line 171 of file matrix.h.
dvector
typedef array<double> upc::dvector
Definition at line 170 of file matrix.h.
fmatrix
typedef matrix<float> upc::fmatrix
Definition at line 169 of file matrix.h.
fvector
typedef array<float> upc::fvector
Definition at line 168 of file matrix.h.
imatrix
typedef matrix<int> upc::imatrix
Definition at line 167 of file matrix.h.
ivector
typedef array<int> upc::ivector
Definition at line 166 of file matrix.h.
vstring
typedef vector<string> upc::vstring
Definition at line 22 of file filename.h.
Function Documentation
fileInfo()
FileInfo upc::fileInfo (const Path & fname)
Definition at line 154 of file filename.cpp.
References _S_IFDIR, _stati64, upc::FileInfo::DIR, upc::FileInfo::ERR, and upc::FileInfo::REG.
Referenced by upc::Directory::exist(), upc::Filename::exist(), and upc::Filename::size().
getCols()
int upc::getCols (istream & is, vstring & cols)
Definition at line 83 of file filename.cpp.
References upc::ascii::TAB.
keyStroke()
bool upc::keyStroke (char key = 0)
Definition at line 107 of file filename.cpp.
References keyBoardHit().
operator<<() [1/2]
template<class _Ty > std::ostream& upc::operator<< (std::ostream & os, const array< _Ty > & f) inline
Definition at line 46 of file matrix.h.
References upc::array< _Ty >::v().
operator<<() [2/2]
template<class _Ty > std::ostream& upc::operator<< (std::ostream & os, const matrix< _Ty > & f) inline
Definition at line 145 of file matrix.h.
References upc::matrix< _Ty >::ncol(), and upc::matrix< _Ty >::nrow().
operator>>() [1/2]
template<class _Ty > std::istream& upc::operator>> (std::istream & is, array< _Ty > & f) inline
Definition at line 55 of file matrix.h.
References upc::array< _Ty >::v().
operator>>() [2/2]
template<class _Ty > std::istream& upc::operator>> (std::istream & is, matrix< _Ty > & f) inline
Definition at line 156 of file matrix.h.
References upc::matrix< _Ty >::resize().
Variable Documentation
MAX_F0
const float upc::MAX_F0 = 10000.0F
Maximum value of pitch in Hertzs.
Definition at line 11 of file pitch_analyzer.h.
MIN_F0
const float upc::MIN_F0 = 20.0F
Minimum value of pitch in Hertzs.
Definition at line 10 of file pitch_analyzer.h.