Pr치ctica 3 de PAV - detecci칩n de pitch: docopt Namespace Reference
docopt Namespace Reference
Classes
class Argument
class BranchPattern
class Command
struct DocoptArgumentError
struct DocoptExitHelp
struct DocoptExitVersion
struct DocoptLanguageError
class Either
class LeafPattern
class OneOrMore
class Option
class Optional
class OptionsShortcut
class Pattern
struct PatternHasher
struct PatternPointerEquality
class Required
struct value
Typedefs
using PatternList = std::vector< std::shared_ptr< Pattern > >
using UniquePatternSet = std::unordered_set< std::shared_ptr< Pattern >, PatternHasher, PatternPointerEquality >
Functions
std::map< std::string, value > DOCOPT_API docopt_parse (std::string const &doc, std::vector< std::string > const &argv, bool help=true, bool version=true, bool options_first=false)
std::map< std::string, value > DOCOPT_API docopt (std::string const &doc, std::vector< std::string > const &argv, bool help=true, std::string const &version={}, bool options_first=false) noexcept
static std::vector< PatternList > transform (PatternList pattern)
template<class T >
void hash_combine (std::size_t &seed, T const &v)
std::ostream & operator<< (std::ostream &, value const &)
Write out the contents to the ostream.
bool operator== (value const &v1, value const &v2)
bool operator!= (value const &v1, value const &v2)
Typedef Documentation
PatternList
using docopt::PatternList = typedef std::vector<std::shared_ptr<Pattern> >
Definition at line 40 of file docopt_private.h.
UniquePatternSet
using docopt::UniquePatternSet = typedef std::unordered_set<std::shared_ptr<Pattern>, PatternHasher, PatternPointerEquality>
Definition at line 71 of file docopt_private.h.
Function Documentation
docopt()
DOCOPT_INLINE std::map< std::string, value > docopt::docopt (std::string const & doc, std::vector< std::string > const & argv, bool help = true, std::string const & version = {}, bool options_first = false) noexcept
Parse user options from the given string, and exit appropriately
Calls 'docopt_parse' and will terminate the program if any of the exceptions above occur:
DocoptLanguageError - print error and terminate (with exit code -1)
DocoptExitHelp - print usage string and terminate (with exit code 0)
DocoptExitVersion - print version and terminate (with exit code 0)
DocoptArgumentError - print error and usage string and terminate (with exit code -1)
Definition at line 663 of file docopt.cpp.
References docopt_parse(), and run_tests::error.
Referenced by main().
docopt_parse()
DOCOPT_INLINE std::map< std::string, value > docopt::docopt_parse (std::string const & doc, std::vector< std::string > const & argv, bool help = true, bool version = true, bool options_first = false)
Parse user options from the given option string.
Parameters
doc The usage string
argv The user-supplied arguments
help Whether to end early if '-h' or '–help' is in the argv
version Whether to end early if '–version' is in the argv
options_first Whether options must precede all args (true), or if args and options can be arbitrarily mixed.
Exceptions
DocoptLanguageError if the doc usage string had errors itself
DocoptExitHelp if 'help' is true and the user has passed the '–help' argument
DocoptExitVersion if 'version' is true and the user has passed the '–version' argument
DocoptArgumentError if the user's argv did not match the usage patterns
Definition at line 613 of file docopt.cpp.
References create_pattern_tree(), run_tests::error, extras(), docopt::BranchPattern::fix(), anonymous_namespace{docopt_util.h}::join(), docopt::Pattern::leaves(), docopt::Pattern::match(), and parse_argv().
Referenced by docopt().
hash_combine()
template<class T > void docopt::hash_combine (std::size_t & seed, T const & v) inline
Definition at line 114 of file docopt_util.h.
Referenced by docopt::value::hash(), docopt::LeafPattern::hash(), docopt::BranchPattern::hash(), and docopt::Option::hash().
operator!=()
bool docopt::operator!= (value const & v1, value const & v2) inline
Definition at line 335 of file docopt_value.h.
operator<<()
DOCOPT_INLINE std::ostream & docopt::operator<< (std::ostream & os, value const & val)
Write out the contents to the ostream.
Definition at line 27 of file docopt.cpp.
References docopt::value::asBool(), docopt::value::asLong(), docopt::value::asString(), docopt::value::asStringList(), docopt::value::isBool(), docopt::value::isLong(), docopt::value::isString(), and docopt::value::isStringList().
operator==()
bool docopt::operator== (value const & v1, value const & v2) inline
Definition at line 310 of file docopt_value.h.
References docopt::value::Bool, docopt::value::Variant::boolValue, docopt::value::Empty, docopt::value::kind, docopt::value::Long, docopt::value::Variant::longValue, docopt::value::String, docopt::value::StringList, docopt::value::Variant::strList, docopt::value::Variant::strValue, and docopt::value::variant.
transform()
static std::vector<PatternList> docopt::transform (PatternList pattern) inline static
Definition at line 337 of file docopt_private.h.
References docopt::BranchPattern::children().
Referenced by create_pattern_tree(), docopt::BranchPattern::fix_repeating_arguments(), flat_filter(), and longOptions().