Pr치ctica 3 de PAV - detecci칩n de pitch: docopt::value Struct Reference
docopt::value Struct Reference
#include "docopt_value.h"
Classes
union Variant
Public Member Functions
value ()
An empty value.
value (std::string)
value (std::vector< std::string >)
value (bool)
value (long)
value (int v)
~value ()
value (value const &)
value (value &&) noexcept
value & operator= (value const &)
value & operator= (value &&) noexcept
operator bool () const
bool isBool () const
bool isString () const
bool isLong () const
bool isStringList () const
bool asBool () const
long asLong () const
std::string const & asString () const
std::vector< std::string > const & asStringList () const
size_t hash () const noexcept
Private Types
enum Kind {
Kind::Empty, Kind::Bool, Kind::Long, Kind::String,
Kind::StringList
}
Private Member Functions
void throwIfNotKind (Kind expected) const
Static Private Member Functions
static const char * kindAsString (Kind kind)
Private Attributes
Kind kind = Kind::Empty
Variant variant {}
Friends
bool operator== (value const &, value const &)
bool operator!= (value const &, value const &)
Detailed Description
A generic type to hold the various types that can be produced by docopt.
This type can be one of: {bool, long, string, vector<string>}, or empty.
Definition at line 23 of file docopt_value.h.
Member Enumeration Documentation
Kind
enum docopt::value::Kind strong private
Enumerator
Empty
Bool
Long
String
StringList
Definition at line 62 of file docopt_value.h.
Constructor & Destructor Documentation
value() [1/8]
docopt::value::value () inline
An empty value.
Definition at line 25 of file docopt_value.h.
value() [2/8]
docopt::value::value (std::string v) inline
Definition at line 136 of file docopt_value.h.
References docopt::value::Variant::strValue, and variant.
value() [3/8]
docopt::value::value (std::vector< std::string > v) inline
Definition at line 143 of file docopt_value.h.
References docopt::value::Variant::strList, and variant.
value() [4/8]
docopt::value::value (bool v) inline explicit
Definition at line 122 of file docopt_value.h.
References docopt::value::Variant::boolValue, and variant.
value() [5/8]
docopt::value::value (long v) inline explicit
Definition at line 129 of file docopt_value.h.
References docopt::value::Variant::longValue, and variant.
value() [6/8]
docopt::value::value (int v) inline explicit
Definition at line 32 of file docopt_value.h.
~value()
docopt::value::~value () inline
Definition at line 204 of file docopt_value.h.
References Bool, Empty, kind, Long, String, StringList, docopt::value::Variant::strList, docopt::value::Variant::strValue, and variant.
value() [7/8]
docopt::value::value (value const & other) inline
Definition at line 150 of file docopt_value.h.
References Bool, docopt::value::Variant::boolValue, Empty, kind, Long, docopt::value::Variant::longValue, String, StringList, docopt::value::Variant::strList, docopt::value::Variant::strValue, and variant.
value() [8/8]
docopt::value::value (value && other) inline noexcept
Definition at line 177 of file docopt_value.h.
Member Function Documentation
asBool()
bool docopt::value::asBool () const inline
Definition at line 271 of file docopt_value.h.
References Bool, docopt::value::Variant::boolValue, throwIfNotKind(), and variant.
Referenced by docopt::operator<<().
asLong()
long docopt::value::asLong () const inline
Definition at line 278 of file docopt_value.h.
References kind, Long, docopt::value::Variant::longValue, String, docopt::value::Variant::strValue, throwIfNotKind(), and variant.
Referenced by docopt::operator<<().
asString()
std::string const & docopt::value::asString () const inline
Definition at line 296 of file docopt_value.h.
References String, docopt::value::Variant::strValue, throwIfNotKind(), and variant.
Referenced by docopt::BranchPattern::fix_repeating_arguments(), and docopt::operator<<().
asStringList()
std::vector< std::string > const & docopt::value::asStringList () const inline
Definition at line 303 of file docopt_value.h.
References StringList, docopt::value::Variant::strList, throwIfNotKind(), and variant.
Referenced by docopt::operator<<().
hash()
size_t docopt::value::hash () const inline noexcept
Definition at line 244 of file docopt_value.h.
References Bool, docopt::value::Variant::boolValue, Empty, docopt::hash_combine(), kind, Long, docopt::value::Variant::longValue, String, StringList, docopt::value::Variant::strList, docopt::value::Variant::strValue, and variant.
isBool()
bool docopt::value::isBool () const inline
Definition at line 44 of file docopt_value.h.
References Bool, and kind.
Referenced by docopt::operator<<().
isLong()
bool docopt::value::isLong () const inline
Definition at line 46 of file docopt_value.h.
References kind, and Long.
Referenced by docopt::operator<<().
isString()
bool docopt::value::isString () const inline
Definition at line 45 of file docopt_value.h.
References kind, and String.
Referenced by docopt::BranchPattern::fix_repeating_arguments(), and docopt::operator<<().
isStringList()
bool docopt::value::isStringList () const inline
Definition at line 47 of file docopt_value.h.
References kind, and StringList.
Referenced by docopt::BranchPattern::fix_repeating_arguments(), and docopt::operator<<().
kindAsString()
static const char* docopt::value::kindAsString (Kind kind) inline static private
Definition at line 80 of file docopt_value.h.
References Bool, Empty, kind, Long, String, and StringList.
Referenced by throwIfNotKind().
operator bool()
docopt::value::operator bool () const inline explicit
Definition at line 41 of file docopt_value.h.
References Empty, and kind.
operator=() [1/2]
value & docopt::value::operator= (value && other) inline noexcept
Definition at line 231 of file docopt_value.h.
operator=() [2/2]
value & docopt::value::operator= (value const & other) inline
Definition at line 225 of file docopt_value.h.
throwIfNotKind()
void docopt::value::throwIfNotKind (Kind expected) const inline private
Definition at line 91 of file docopt_value.h.
References run_tests::error, kind, and kindAsString().
Referenced by asBool(), asLong(), asString(), and asStringList().
Friends And Related Function Documentation
operator!=
bool operator!= (value const & v1, value const & v2) friend
Definition at line 335 of file docopt_value.h.
operator==
bool operator== (value const & v1, value const & v2) friend
Definition at line 310 of file docopt_value.h.
Member Data Documentation
kind
Kind docopt::value::kind = Kind::Empty private
Definition at line 103 of file docopt_value.h.
Referenced by asLong(), hash(), isBool(), isLong(), isString(), isStringList(), kindAsString(), operator bool(), docopt::operator==(), throwIfNotKind(), value(), and ~value().
variant
Variant docopt::value::variant {} private
Definition at line 104 of file docopt_value.h.
Referenced by asBool(), asLong(), asString(), asStringList(), hash(), docopt::operator==(), value(), and ~value().
The documentation for this struct was generated from the following file:
/Users/davidbonet/Desktop/p3-priv/src/pav/docopt_cpp/docopt_value.h