Pr치ctica 3 de PAV - detecci칩n de pitch: upc::array< _Ty > Class Template Reference
upc::array< _Ty > Class Template Reference
#include "matrix.h"
Public Types
typedef array< _Ty > _Myt
typedef uint32_t size_type
typedef _A::pointer _Tptr
typedef _A::const_pointer _Ctptr
typedef _A::reference reference
typedef _A::const_reference const_reference
Public Member Functions
array (unsigned int size=0)
_Ctptr v () const
_Tptr v ()
void reset ()
Private Types
typedef std::valarray< _Ty > Tvalarray
typedef std::allocator< _Ty > _A
Detailed Description
template<class _Ty>
class upc::array< _Ty >
Definition at line 19 of file matrix.h.
Member Typedef Documentation
_A
template<class _Ty > typedef std::allocator<_Ty> upc::array< _Ty >::_A private
Definition at line 22 of file matrix.h.
_Ctptr
template<class _Ty > typedef _A::const_pointer upc::array< _Ty >::_Ctptr
Definition at line 28 of file matrix.h.
_Myt
template<class _Ty > typedef array<_Ty> upc::array< _Ty >::_Myt
Definition at line 24 of file matrix.h.
_Tptr
template<class _Ty > typedef _A::pointer upc::array< _Ty >::_Tptr
Definition at line 27 of file matrix.h.
const_reference
template<class _Ty > typedef _A::const_reference upc::array< _Ty >::const_reference
Definition at line 30 of file matrix.h.
reference
template<class _Ty > typedef _A::reference upc::array< _Ty >::reference
Definition at line 29 of file matrix.h.
size_type
template<class _Ty > typedef uint32_t upc::array< _Ty >::size_type
Definition at line 26 of file matrix.h.
Tvalarray
template<class _Ty > typedef std::valarray<_Ty> upc::array< _Ty >::Tvalarray private
Definition at line 21 of file matrix.h.
Constructor & Destructor Documentation
array()
template<class _Ty > upc::array< _Ty >::array (unsigned int size = 0) inline explicit
Definition at line 31 of file matrix.h.
Member Function Documentation
reset()
template<class _Ty > void upc::array< _Ty >::reset () inline
Definition at line 39 of file matrix.h.
v() [1/2]
template<class _Ty > _Tptr upc::array< _Ty >::v () inline
Definition at line 36 of file matrix.h.
v() [2/2]
template<class _Ty > _Ctptr upc::array< _Ty >::v () const inline
Definition at line 32 of file matrix.h.
Referenced by upc::matrix< _Ty >::m(), upc::operator<<(), upc::operator>>(), and upc::array< _Tptr >::v().
The documentation for this class was generated from the following file:
/Users/davidbonet/Desktop/p3-pso/src/include/matrix.h