Pr치ctica 3 de PAV - detecci칩n de pitch: upc::matrix< _Ty > Class Template Reference
upc::matrix< _Ty > Class Template Reference
#include "matrix.h"
Public Types
typedef Tvector::size_type size_type
Public Member Functions
matrix (size_type nrow=0, size_type ncol=0)
matrix (const _Myt &o)
size_type nrow () const
size_type ncol () const
_Ctptr operator[] (int i) const
_Tptr operator[] (int i)
const _Ctptr * m () const
_Tptr * m ()
void reset ()
void resize (size_type nrow, size_type ncol)
_Myt & operator= (const _Myt &other)
Private Types
typedef matrix< _Ty > _Myt
typedef array< _Ty > Tvector
typedef Tvector::_Ctptr _Ctptr
typedef Tvector::_Tptr _Tptr
typedef array< _Tptr > Pvector
Private Attributes
Tvector m_v
Pvector m_p
size_type m_nrow
size_type m_ncol
Detailed Description
template<class _Ty>
class upc::matrix< _Ty >
Definition at line 66 of file matrix.h.
Member Typedef Documentation
_Ctptr
template<class _Ty > typedef Tvector::_Ctptr upc::matrix< _Ty >::_Ctptr private
Definition at line 70 of file matrix.h.
_Myt
template<class _Ty > typedef matrix<_Ty> upc::matrix< _Ty >::_Myt private
Definition at line 68 of file matrix.h.
_Tptr
template<class _Ty > typedef Tvector::_Tptr upc::matrix< _Ty >::_Tptr private
Definition at line 71 of file matrix.h.
Pvector
template<class _Ty > typedef array<_Tptr> upc::matrix< _Ty >::Pvector private
Definition at line 72 of file matrix.h.
size_type
template<class _Ty > typedef Tvector::size_type upc::matrix< _Ty >::size_type
Definition at line 74 of file matrix.h.
Tvector
template<class _Ty > typedef array<_Ty> upc::matrix< _Ty >::Tvector private
Definition at line 69 of file matrix.h.
Constructor & Destructor Documentation
matrix() [1/2]
template<class _Ty > upc::matrix< _Ty >::matrix (size_type nrow = 0, size_type ncol = 0) inline explicit
Definition at line 75 of file matrix.h.
References upc::matrix< _Ty >::m_p, upc::matrix< _Ty >::m_v, upc::matrix< _Ty >::ncol(), and upc::matrix< _Ty >::nrow().
matrix() [2/2]
template<class _Ty > upc::matrix< _Ty >::matrix (const _Myt & o) inline
Definition at line 84 of file matrix.h.
References upc::matrix< _Ty >::m_ncol, upc::matrix< _Ty >::m_nrow, upc::matrix< _Ty >::m_p, and upc::matrix< _Ty >::m_v.
Member Function Documentation
m() [1/2]
template<class _Ty > _Tptr* upc::matrix< _Ty >::m () inline
Definition at line 99 of file matrix.h.
References upc::matrix< _Ty >::m_p, and upc::array< _Ty >::v().
m() [2/2]
template<class _Ty > const _Ctptr* upc::matrix< _Ty >::m () const inline
Definition at line 98 of file matrix.h.
References upc::matrix< _Ty >::m_p, and upc::array< _Ty >::v().
ncol()
template<class _Ty > size_type upc::matrix< _Ty >::ncol () const inline
Definition at line 95 of file matrix.h.
References upc::matrix< _Ty >::m_ncol.
Referenced by upc::matrix< _Ty >::matrix(), upc::operator<<(), and upc::matrix< _Ty >::resize().
nrow()
template<class _Ty > size_type upc::matrix< _Ty >::nrow () const inline
Definition at line 94 of file matrix.h.
References upc::matrix< _Ty >::m_nrow.
Referenced by upc::matrix< _Ty >::matrix(), upc::operator<<(), and upc::matrix< _Ty >::resize().
operator=()
template<class _Ty > _Myt& upc::matrix< _Ty >::operator= (const _Myt & other) inline
Definition at line 125 of file matrix.h.
References upc::matrix< _Ty >::m_ncol, upc::matrix< _Ty >::m_nrow, upc::matrix< _Ty >::m_p, and upc::matrix< _Ty >::m_v.
operator[]() [1/2]
template<class _Ty > _Tptr upc::matrix< _Ty >::operator[] (int i) inline
Definition at line 97 of file matrix.h.
References upc::matrix< _Ty >::m_p.
operator[]() [2/2]
template<class _Ty > _Ctptr upc::matrix< _Ty >::operator[] (int i) const inline
Definition at line 96 of file matrix.h.
References upc::matrix< _Ty >::m_p.
reset()
template<class _Ty > void upc::matrix< _Ty >::reset () inline
Definition at line 100 of file matrix.h.
References upc::matrix< _Ty >::m_v.
resize()
template<class _Ty > void upc::matrix< _Ty >::resize (size_type nrow, size_type ncol) inline
Definition at line 101 of file matrix.h.
References upc::matrix< _Ty >::m_ncol, upc::matrix< _Ty >::m_nrow, upc::matrix< _Ty >::m_p, upc::matrix< _Ty >::m_v, upc::matrix< _Ty >::ncol(), and upc::matrix< _Ty >::nrow().
Referenced by upc::operator>>().
Member Data Documentation
m_ncol
template<class _Ty > size_type upc::matrix< _Ty >::m_ncol private
Definition at line 141 of file matrix.h.
Referenced by upc::matrix< _Ty >::matrix(), upc::matrix< _Ty >::ncol(), upc::matrix< _Ty >::operator=(), and upc::matrix< _Ty >::resize().
m_nrow
template<class _Ty > size_type upc::matrix< _Ty >::m_nrow private
Definition at line 141 of file matrix.h.
Referenced by upc::matrix< _Ty >::matrix(), upc::matrix< _Ty >::nrow(), upc::matrix< _Ty >::operator=(), and upc::matrix< _Ty >::resize().
m_p
template<class _Ty > Pvector upc::matrix< _Ty >::m_p private
Definition at line 140 of file matrix.h.
Referenced by upc::matrix< _Ty >::m(), upc::matrix< _Ty >::matrix(), upc::matrix< _Ty >::operator=(), upc::matrix< _Ty >::operator[](), and upc::matrix< _Ty >::resize().
m_v
template<class _Ty > Tvector upc::matrix< _Ty >::m_v private
Definition at line 139 of file matrix.h.
Referenced by upc::matrix< _Ty >::matrix(), upc::matrix< _Ty >::operator=(), upc::matrix< _Ty >::reset(), and upc::matrix< _Ty >::resize().
The documentation for this class was generated from the following file:
/Users/davidbonet/Desktop/p3-pso/src/include/matrix.h