Pr치ctica 3 de PAV - detecci칩n de pitch: docopt::BranchPattern Class Reference
docopt::BranchPattern Class Reference
#include "docopt_private.h"
Public Member Functions
BranchPattern (PatternList children={})
Pattern & fix ()
virtual std::string const & name () const override
virtual value const & getValue () const
virtual std::vector< Pattern * > flat (bool(*filter)(Pattern const *)) override
virtual void collect_leaves (std::vector< LeafPattern * > &lst) override final
void setChildren (PatternList children)
PatternList const & children () const
virtual void fix_identities (UniquePatternSet &patterns)
virtual size_t hash () const override
Public Member Functions inherited from docopt::Pattern
std::vector< LeafPattern * > leaves ()
virtual bool match (PatternList &left, std::vector< std::shared_ptr< LeafPattern >> &collected) const =0
virtual bool hasValue () const
virtual ~Pattern ()=default
Protected Attributes
PatternList fChildren
Private Member Functions
void fix_repeating_arguments ()
Detailed Description
Definition at line 140 of file docopt_private.h.
Constructor & Destructor Documentation
BranchPattern()
docopt::BranchPattern::BranchPattern (PatternList children = {}) inline
Definition at line 143 of file docopt_private.h.
Member Function Documentation
children()
PatternList const& docopt::BranchPattern::children () const inline
Definition at line 185 of file docopt_private.h.
References fChildren.
Referenced by fix_repeating_arguments(), setChildren(), and docopt::transform().
collect_leaves()
virtual void docopt::BranchPattern::collect_leaves (std::vector< LeafPattern * > & lst) inline final override virtual
Implements docopt::Pattern.
Definition at line 175 of file docopt_private.h.
References fChildren.
fix()
Pattern& docopt::BranchPattern::fix () inline
Definition at line 147 of file docopt_private.h.
References fix_identities(), and fix_repeating_arguments().
Referenced by docopt::docopt_parse().
fix_identities()
virtual void docopt::BranchPattern::fix_identities (UniquePatternSet & patterns) inline virtual
Definition at line 187 of file docopt_private.h.
References fChildren.
Referenced by fix().
fix_repeating_arguments()
void docopt::BranchPattern::fix_repeating_arguments () inline private
Definition at line 395 of file docopt_private.h.
References docopt::value::asString(), children(), docopt::LeafPattern::getValue(), docopt::value::isString(), docopt::value::isStringList(), docopt::LeafPattern::setValue(), anonymous_namespace{docopt_util.h}::split(), and docopt::transform().
Referenced by fix().
flat()
virtual std::vector<Pattern*> docopt::BranchPattern::flat (bool(*)(Pattern const *) filter) inline override virtual
Implements docopt::Pattern.
Definition at line 162 of file docopt_private.h.
References fChildren.
getValue()
virtual value const& docopt::BranchPattern::getValue () const inline virtual
Definition at line 158 of file docopt_private.h.
hash()
virtual size_t docopt::BranchPattern::hash () const inline override virtual
Implements docopt::Pattern.
Definition at line 203 of file docopt_private.h.
References fChildren, and docopt::hash_combine().
name()
virtual std::string const& docopt::BranchPattern::name () const inline override virtual
Implements docopt::Pattern.
Definition at line 154 of file docopt_private.h.
setChildren()
void docopt::BranchPattern::setChildren (PatternList children) inline
Definition at line 181 of file docopt_private.h.
References children(), and fChildren.
Member Data Documentation
fChildren
PatternList docopt::BranchPattern::fChildren protected
Definition at line 215 of file docopt_private.h.
Referenced by children(), collect_leaves(), fix_identities(), flat(), hash(), docopt::Required::match(), docopt::Optional::match(), docopt::OneOrMore::match(), docopt::Either::match(), and setChildren().
The documentation for this class was generated from the following file:
/Users/davidbonet/Desktop/p3-pso/src/pav/docopt_cpp/docopt_private.h