Pr치ctica 3 de PAV - detecci칩n de pitch: upc::Filename Class Reference
upc::Filename Class Reference
#include "filename.h"
Public Member Functions
Filename ()
Filename (const Path &p)
Filename (const string &p)
Filename (const char *p)
bool checkDir (bool create=true) const
bool exist () const
Directory path () const
long long size () const
virtual ~Filename ()
Public Member Functions inherited from upc::Path
Path ()
Path (const string &str)
Path (const char *str)
virtual ~Path ()
Detailed Description
Definition at line 84 of file filename.h.
Constructor & Destructor Documentation
Filename() [1/4]
upc::Filename::Filename () inline
Definition at line 86 of file filename.h.
Filename() [2/4]
upc::Filename::Filename (const Path & p) inline
Definition at line 87 of file filename.h.
Filename() [3/4]
upc::Filename::Filename (const string & p) inline
Definition at line 88 of file filename.h.
Filename() [4/4]
upc::Filename::Filename (const char * p) inline
Definition at line 89 of file filename.h.
~Filename()
virtual upc::Filename::~Filename () inline virtual
Definition at line 94 of file filename.h.
Member Function Documentation
checkDir()
bool upc::Filename::checkDir (bool create = true) const
Definition at line 182 of file filename.cpp.
References upc::Directory::exist(), upc::Directory::make(), and path().
exist()
bool upc::Filename::exist () const
Definition at line 169 of file filename.cpp.
References upc::fileInfo(), upc::FileInfo::REG, and upc::FileInfo::type().
path()
Directory upc::Filename::path () const
Definition at line 191 of file filename.cpp.
Referenced by checkDir().
size()
long long upc::Filename::size () const
Definition at line 175 of file filename.cpp.
References upc::fileInfo(), and upc::FileInfo::size().
The documentation for this class was generated from the following files:
/Users/davidbonet/Desktop/p3-pso/src/include/filename.h
/Users/davidbonet/Desktop/p3-pso/src/pav/filename.cpp