Pr치ctica 3 de PAV - detecci칩n de pitch: ffft::FFTReal< DT > Class Template Reference
ffft::FFTReal< DT > Class Template Reference
#include "FFTReal.h"
Public Types
enum { MAX_BIT_DEPTH = 30 }
typedef DT DataType
Public Member Functions
FFTReal (long length)
virtual ~FFTReal ()
long get_length () const
void do_fft (DataType f[], const DataType x[]) const
void do_ifft (const DataType f[], DataType x[]) const
void rescale (DataType x[]) const
DataType * use_buffer () const
Private Types
enum { TRIGO_BD_LIMIT = 12 }
typedef OscSinCos< DataType > OscType
Private Member Functions
void init_br_lut ()
void init_trigo_lut ()
void init_trigo_osc ()
const ffft_FORCEINLINE long * get_br_ptr () const
const ffft_FORCEINLINE DataType * get_trigo_ptr (int level) const
ffft_FORCEINLINE long get_trigo_level_index (int level) const
void compute_fft_general (DataType f[], const DataType x[]) const
void compute_direct_pass_1_2 (DataType df[], const DataType x[]) const
void compute_direct_pass_3 (DataType df[], const DataType sf[]) const
void compute_direct_pass_n (DataType df[], const DataType sf[], int pass) const
void compute_direct_pass_n_lut (DataType df[], const DataType sf[], int pass) const
void compute_direct_pass_n_osc (DataType df[], const DataType sf[], int pass) const
void compute_ifft_general (const DataType f[], DataType x[]) const
void compute_inverse_pass_n (DataType df[], const DataType sf[], int pass) const
void compute_inverse_pass_n_osc (DataType df[], const DataType sf[], int pass) const
void compute_inverse_pass_n_lut (DataType df[], const DataType sf[], int pass) const
void compute_inverse_pass_3 (DataType df[], const DataType sf[]) const
void compute_inverse_pass_1_2 (DataType x[], const DataType sf[]) const
FFTReal ()
FFTReal (const FFTReal &other)
FFTReal & operator= (const FFTReal &other)
bool operator== (const FFTReal &other)
bool operator!= (const FFTReal &other)
Private Attributes
const long _length
const int _nbr_bits
DynArray< long > _br_lut
DynArray< DataType > _trigo_lut
DynArray< DataType > _buffer
DynArray< OscType > _trigo_osc
Detailed Description
template<class DT>
class ffft::FFTReal< DT >
Definition at line 55 of file FFTReal.h.
Member Typedef Documentation
DataType
template<class DT > typedef DT ffft::FFTReal< DT >::DataType
Definition at line 77 of file FFTReal.h.
OscType
template<class DT > typedef OscSinCos<DataType> ffft::FFTReal< DT >::OscType private
Definition at line 103 of file FFTReal.h.
Member Enumeration Documentation
anonymous enum
template<class DT > anonymous enum
Enumerator
MAX_BIT_DEPTH
Definition at line 75 of file FFTReal.h.
anonymous enum
template<class DT > anonymous enum private
Enumerator
TRIGO_BD_LIMIT
Definition at line 101 of file FFTReal.h.
Constructor & Destructor Documentation
FFTReal() [1/3]
template<class DT > ffft::FFTReal< DT >::FFTReal (long length) explicit
Definition at line 90 of file FFTReal.hpp.
References ffft::FFTReal_is_pow2().
~FFTReal()
template<class DT > virtual ffft::FFTReal< DT >::~FFTReal () inline virtual
Definition at line 80 of file FFTReal.h.
FFTReal() [2/3]
template<class DT > ffft::FFTReal< DT >::FFTReal () private
FFTReal() [3/3]
template<class DT > ffft::FFTReal< DT >::FFTReal (const FFTReal< DT > & other) private
Member Function Documentation
compute_direct_pass_1_2()
template<class DT > void ffft::FFTReal< DT >::compute_direct_pass_1_2 (DataType df[], const DataType x[]) const inline private
Definition at line 464 of file FFTReal.hpp.
compute_direct_pass_3()
template<class DT > void ffft::FFTReal< DT >::compute_direct_pass_3 (DataType df[], const DataType sf[]) const inline private
Definition at line 497 of file FFTReal.hpp.
References ffft::SQRT2.
compute_direct_pass_n()
template<class DT > void ffft::FFTReal< DT >::compute_direct_pass_n (DataType df[], const DataType sf[], int pass) const inline private
Definition at line 530 of file FFTReal.hpp.
compute_direct_pass_n_lut()
template<class DT > void ffft::FFTReal< DT >::compute_direct_pass_n_lut (DataType df[], const DataType sf[], int pass) const inline private
Definition at line 551 of file FFTReal.hpp.
compute_direct_pass_n_osc()
template<class DT > void ffft::FFTReal< DT >::compute_direct_pass_n_osc (DataType df[], const DataType sf[], int pass) const inline private
Definition at line 603 of file FFTReal.hpp.
References ffft::OscSinCos< T >::clear_buffers(), ffft::OscSinCos< T >::get_cos(), ffft::OscSinCos< T >::get_sin(), and ffft::OscSinCos< T >::step().
compute_fft_general()
template<class DT > void ffft::FFTReal< DT >::compute_fft_general (DataType f[], const DataType x[]) const inline private
Definition at line 426 of file FFTReal.hpp.
compute_ifft_general()
template<class DT > void ffft::FFTReal< DT >::compute_ifft_general (const DataType f[], DataType x[]) const inline private
Definition at line 659 of file FFTReal.hpp.
compute_inverse_pass_1_2()
template<class DT > void ffft::FFTReal< DT >::compute_inverse_pass_1_2 (DataType x[], const DataType sf[]) const inline private
Definition at line 864 of file FFTReal.hpp.
compute_inverse_pass_3()
template<class DT > void ffft::FFTReal< DT >::compute_inverse_pass_3 (DataType df[], const DataType sf[]) const inline private
Definition at line 832 of file FFTReal.hpp.
References ffft::SQRT2.
compute_inverse_pass_n()
template<class DT > void ffft::FFTReal< DT >::compute_inverse_pass_n (DataType df[], const DataType sf[], int pass) const inline private
Definition at line 706 of file FFTReal.hpp.
compute_inverse_pass_n_lut()
template<class DT > void ffft::FFTReal< DT >::compute_inverse_pass_n_lut (DataType df[], const DataType sf[], int pass) const inline private
Definition at line 727 of file FFTReal.hpp.
compute_inverse_pass_n_osc()
template<class DT > void ffft::FFTReal< DT >::compute_inverse_pass_n_osc (DataType df[], const DataType sf[], int pass) const inline private
Definition at line 778 of file FFTReal.hpp.
References ffft::OscSinCos< T >::clear_buffers(), ffft::OscSinCos< T >::get_cos(), ffft::OscSinCos< T >::get_sin(), and ffft::OscSinCos< T >::step().
do_fft()
template<class DT > void ffft::FFTReal< DT >::do_fft (DataType f[], const DataType x[]) const
Definition at line 143 of file FFTReal.hpp.
Referenced by main().
do_ifft()
template<class DT > void ffft::FFTReal< DT >::do_ifft (const DataType f[], DataType x[]) const
Definition at line 204 of file FFTReal.hpp.
Referenced by main().
get_br_ptr()
template<class DT > const long * ffft::FFTReal< DT >::get_br_ptr private
Definition at line 397 of file FFTReal.hpp.
get_length()
template<class DT > long ffft::FFTReal< DT >::get_length
Definition at line 119 of file FFTReal.hpp.
get_trigo_level_index()
template<class DT > long ffft::FFTReal< DT >::get_trigo_level_index (int level) const private
Definition at line 415 of file FFTReal.hpp.
get_trigo_ptr()
template<class DT > const FFTReal< DT >::DataType * ffft::FFTReal< DT >::get_trigo_ptr (int level) const private
Definition at line 405 of file FFTReal.hpp.
init_br_lut()
template<class DT > void ffft::FFTReal< DT >::init_br_lut private
Definition at line 326 of file FFTReal.hpp.
init_trigo_lut()
template<class DT > void ffft::FFTReal< DT >::init_trigo_lut private
Definition at line 349 of file FFTReal.hpp.
References ffft::PI.
init_trigo_osc()
template<class DT > void ffft::FFTReal< DT >::init_trigo_osc private
Definition at line 376 of file FFTReal.hpp.
References ffft::PI, and ffft::OscSinCos< T >::set_step().
operator!=()
template<class DT > bool ffft::FFTReal< DT >::operator!= (const FFTReal< DT > & other) private
operator=()
template<class DT > FFTReal& ffft::FFTReal< DT >::operator= (const FFTReal< DT > & other) private
operator==()
template<class DT > bool ffft::FFTReal< DT >::operator== (const FFTReal< DT > & other) private
rescale()
template<class DT > void ffft::FFTReal< DT >::rescale (DataType x[]) const
Definition at line 259 of file FFTReal.hpp.
Referenced by main().
use_buffer()
template<class DT > FFTReal< DT >::DataType * ffft::FFTReal< DT >::use_buffer
Definition at line 310 of file FFTReal.hpp.
Member Data Documentation
_br_lut
template<class DT > DynArray<long> ffft::FFTReal< DT >::_br_lut private
Definition at line 133 of file FFTReal.h.
_buffer
template<class DT > DynArray<DataType> ffft::FFTReal< DT >::_buffer mutable private
Definition at line 137 of file FFTReal.h.
_length
template<class DT > const long ffft::FFTReal< DT >::_length private
Definition at line 130 of file FFTReal.h.
_nbr_bits
template<class DT > const int ffft::FFTReal< DT >::_nbr_bits private
Definition at line 131 of file FFTReal.h.
_trigo_lut
template<class DT > DynArray<DataType> ffft::FFTReal< DT >::_trigo_lut private
Definition at line 135 of file FFTReal.h.
_trigo_osc
template<class DT > DynArray<OscType> ffft::FFTReal< DT >::_trigo_osc mutable private
Definition at line 139 of file FFTReal.h.
The documentation for this class was generated from the following files:
/Users/davidbonet/Desktop/p3-pso/src/include/ffft/FFTReal.h
/Users/davidbonet/Desktop/p3-pso/src/include/ffft/FFTReal.hpp