Pr치ctica 3 de PAV - detecci칩n de pitch: Tokens Class Reference
Tokens Class Reference
Classes
struct OptionError
Public Member Functions
Tokens (std::vector< std::string > tokens, bool isParsingArgv=true)
operator bool () const
std::string const & current () const
std::string the_rest () const
std::string pop ()
bool isParsingArgv () const
Static Public Member Functions
static Tokens from_pattern (std::string const &source)
Private Attributes
std::vector< std::string > fTokens
size_t fIndex = 0
bool fIsParsingArgv
Detailed Description
Definition at line 62 of file docopt.cpp.
Constructor & Destructor Documentation
Tokens()
Tokens::Tokens (std::vector< std::string > tokens, bool isParsingArgv = true) inline
Definition at line 64 of file docopt.cpp.
Member Function Documentation
current()
std::string const& Tokens::current () const inline
Definition at line 120 of file docopt.cpp.
Referenced by parse_argv(), parse_atom(), parse_expr(), parse_long(), parse_seq(), and parse_short().
from_pattern()
static Tokens Tokens::from_pattern (std::string const & source) inline static
Definition at line 73 of file docopt.cpp.
Referenced by parse_pattern().
isParsingArgv()
bool Tokens::isParsingArgv () const inline
Definition at line 140 of file docopt.cpp.
Referenced by parse_long(), and parse_short().
operator bool()
Tokens::operator bool () const inline explicit
Definition at line 69 of file docopt.cpp.
pop()
std::string Tokens::pop () inline
Definition at line 136 of file docopt.cpp.
Referenced by parse_argv(), parse_atom(), parse_expr(), parse_long(), parse_seq(), and parse_short().
the_rest()
std::string Tokens::the_rest () const inline
Definition at line 128 of file docopt.cpp.
References anonymous_namespace{docopt_util.h}::join().
Member Data Documentation
fIndex
size_t Tokens::fIndex = 0 private
Definition at line 146 of file docopt.cpp.
fIsParsingArgv
bool Tokens::fIsParsingArgv private
Definition at line 147 of file docopt.cpp.
fTokens
std::vector<std::string> Tokens::fTokens private
Definition at line 145 of file docopt.cpp.
The documentation for this class was generated from the following file:
/Users/davidbonet/Desktop/p3-pso/src/pav/docopt_cpp/docopt.cpp