Pr치ctica 3 de PAV - detecci칩n de pitch: docopt::Pattern Class Reference
docopt::Pattern Class Reference abstract
#include "docopt_private.h"
Public Member Functions
virtual std::vector< Pattern * > flat (bool(*filter)(Pattern const *))=0
virtual void collect_leaves (std::vector< LeafPattern * > &)=0
std::vector< LeafPattern * > leaves ()
virtual bool match (PatternList &left, std::vector< std::shared_ptr< LeafPattern >> &collected) const =0
virtual std::string const & name () const =0
virtual bool hasValue () const
virtual size_t hash () const =0
virtual ~Pattern ()=default
Detailed Description
Definition at line 74 of file docopt_private.h.
Constructor & Destructor Documentation
~Pattern()
virtual docopt::Pattern::~Pattern () virtual default
Member Function Documentation
collect_leaves()
virtual void docopt::Pattern::collect_leaves (std::vector< LeafPattern * > &) pure virtual
Implemented in docopt::BranchPattern, and docopt::LeafPattern.
Referenced by leaves().
flat()
virtual std::vector<Pattern*> docopt::Pattern::flat (bool(*)(Pattern const *) filter) pure virtual
Implemented in docopt::BranchPattern, and docopt::LeafPattern.
Referenced by flat_filter().
hash()
virtual size_t docopt::Pattern::hash () const pure virtual
Implemented in docopt::Option, docopt::BranchPattern, and docopt::LeafPattern.
hasValue()
virtual bool docopt::Pattern::hasValue () const inline virtual
Reimplemented in docopt::LeafPattern.
Definition at line 90 of file docopt_private.h.
leaves()
std::vector< LeafPattern * > docopt::Pattern::leaves () inline
Definition at line 330 of file docopt_private.h.
References collect_leaves().
Referenced by docopt::docopt_parse().
match()
virtual bool docopt::Pattern::match (PatternList & left, std::vector< std::shared_ptr< LeafPattern >> & collected) const pure virtual
Implemented in docopt::Either, docopt::OneOrMore, docopt::Optional, docopt::Required, and docopt::LeafPattern.
Referenced by docopt::docopt_parse().
name()
virtual std::string const& docopt::Pattern::name () const pure virtual
Implemented in docopt::BranchPattern, and docopt::LeafPattern.
The documentation for this class was generated from the following file:
/Users/davidbonet/Desktop/p3-pso/src/pav/docopt_cpp/docopt_private.h