Pr치ctica 3 de PAV - detecci칩n de pitch: /Users/davidbonet/Desktop/p3-pso/src/pav/docopt_cpp/docopt.cpp File Reference
docopt.cpp File Reference
#include "docopt.h"
#include "docopt_util.h"
#include "docopt_private.h"
#include "docopt_value.h"
#include <vector>
#include <unordered_set>
#include <unordered_map>
#include <map>
#include <string>
#include <iostream>
#include <cassert>
#include <cstddef>
Classes
class Tokens
struct Tokens::OptionError
Functions
template<typename T >
std::vector< T * > flat_filter (Pattern &pattern)
static std::vector< std::string > parse_section (std::string const &name, std::string const &source)
static bool is_argument_spec (std::string const &token)
template<typename I >
std::vector< std::string > longOptions (I iter, I end)
static PatternList parse_long (Tokens &tokens, std::vector< Option > &options)
static PatternList parse_short (Tokens &tokens, std::vector< Option > &options)
static PatternList parse_expr (Tokens &tokens, std::vector< Option > &options)
static PatternList parse_atom (Tokens &tokens, std::vector< Option > &options)
static PatternList parse_seq (Tokens &tokens, std::vector< Option > &options)
static std::shared_ptr< Pattern > maybe_collapse_to_required (PatternList &&seq)
static std::shared_ptr< Pattern > maybe_collapse_to_either (PatternList &&seq)
static Required parse_pattern (std::string const &source, std::vector< Option > &options)
static std::string formal_usage (std::string const &section)
static PatternList parse_argv (Tokens tokens, std::vector< Option > &options, bool options_first)
std::vector< Option > parse_defaults (std::string const &doc)
static bool isOptionSet (PatternList const &options, std::string const &opt1, std::string const &opt2="")
static void extras (bool help, bool version, PatternList const &options)
static std::pair< Required, std::vector< Option > > create_pattern_tree (std::string const &doc)
Function Documentation
create_pattern_tree()
static std::pair<Required, std::vector<Option> > create_pattern_tree (std::string const & doc) static
Definition at line 569 of file docopt.cpp.
References formal_usage(), parse_defaults(), parse_pattern(), parse_section(), and docopt::transform().
Referenced by docopt::docopt_parse().
extras()
static void extras (bool help, bool version, PatternList const & options) static
Definition at line 558 of file docopt.cpp.
References isOptionSet().
Referenced by docopt::docopt_parse().
flat_filter()
template<typename T > std::vector<T*> flat_filter (Pattern & pattern)
Definition at line 152 of file docopt.cpp.
References docopt::Pattern::flat(), and docopt::transform().
formal_usage()
static std::string formal_usage (std::string const & section) static
Definition at line 471 of file docopt.cpp.
References anonymous_namespace{docopt_util.h}::split().
Referenced by create_pattern_tree().
is_argument_spec()
static bool is_argument_spec (std::string const & token) static
Definition at line 190 of file docopt.cpp.
Referenced by parse_atom().
isOptionSet()
static bool isOptionSet (PatternList const & options, std::string const & opt1, std::string const & opt2 = "") static
Definition at line 548 of file docopt.cpp.
Referenced by extras().
longOptions()
template<typename I > std::vector<std::string> longOptions (I iter, I end)
Definition at line 204 of file docopt.cpp.
References docopt::transform().
Referenced by parse_long().
maybe_collapse_to_either()
static std::shared_ptr<Pattern> maybe_collapse_to_either (PatternList && seq) static
Definition at line 429 of file docopt.cpp.
Referenced by parse_expr().
maybe_collapse_to_required()
static std::shared_ptr<Pattern> maybe_collapse_to_required (PatternList && seq) static
Definition at line 421 of file docopt.cpp.
Referenced by parse_expr().
parse_argv()
static PatternList parse_argv (Tokens tokens, std::vector< Option > & options, bool options_first) static
Definition at line 489 of file docopt.cpp.
References Tokens::current(), parse_long(), parse_short(), Tokens::pop(), and anonymous_namespace{docopt_util.h}::starts_with().
Referenced by docopt::docopt_parse().
parse_atom()
static PatternList parse_atom (Tokens & tokens, std::vector< Option > & options) static
Definition at line 350 of file docopt.cpp.
References Tokens::current(), is_argument_spec(), parse_expr(), parse_long(), parse_short(), Tokens::pop(), and anonymous_namespace{docopt_util.h}::starts_with().
Referenced by parse_seq().
parse_defaults()
std::vector<Option> parse_defaults (std::string const & doc)
Definition at line 526 of file docopt.cpp.
References docopt::Option::parse(), parse_section(), anonymous_namespace{docopt_util.h}::regex_split(), and anonymous_namespace{docopt_util.h}::starts_with().
Referenced by create_pattern_tree().
parse_expr()
PatternList parse_expr (Tokens & tokens, std::vector< Option > & options) static
Definition at line 437 of file docopt.cpp.
References Tokens::current(), maybe_collapse_to_either(), maybe_collapse_to_required(), parse_seq(), and Tokens::pop().
Referenced by parse_atom(), and parse_pattern().
parse_long()
static PatternList parse_long (Tokens & tokens, std::vector< Option > & options) static
Definition at line 212 of file docopt.cpp.
References Tokens::current(), run_tests::error, Tokens::isParsingArgv(), anonymous_namespace{docopt_util.h}::join(), longOptions(), anonymous_namespace{docopt_util.h}::partition(), Tokens::pop(), and anonymous_namespace{docopt_util.h}::starts_with().
Referenced by parse_argv(), and parse_atom().
parse_pattern()
static Required parse_pattern (std::string const & source, std::vector< Option > & options) static
Definition at line 458 of file docopt.cpp.
References Tokens::from_pattern(), and parse_expr().
Referenced by create_pattern_tree().
parse_section()
static std::vector<std::string> parse_section (std::string const & name, std::string const & source) static
Definition at line 165 of file docopt.cpp.
Referenced by create_pattern_tree(), and parse_defaults().
parse_seq()
static PatternList parse_seq (Tokens & tokens, std::vector< Option > & options) static
Definition at line 397 of file docopt.cpp.
References Tokens::current(), parse_atom(), and Tokens::pop().
Referenced by parse_expr().
parse_short()
static PatternList parse_short (Tokens & tokens, std::vector< Option > & options) static
Definition at line 284 of file docopt.cpp.
References Tokens::current(), run_tests::error, Tokens::isParsingArgv(), Tokens::pop(), and anonymous_namespace{docopt_util.h}::starts_with().
Referenced by parse_argv(), and parse_atom().