Pr치ctica 3 de PAV - detecci칩n de pitch: /Users/davidbonet/Desktop/p3-pso/src/pav/filename.cpp File Reference
filename.cpp File Reference
#include <limits.h>
#include <string.h>
#include <iostream>
#include <fstream>
#include <sys/types.h>
#include <sys/stat.h>
#include "filename.h"
#include <sys/select.h>
#include <termios.h>
Namespaces
upc
Name space of UPC.
Macros
#define _stati64 stat
#define _S_IFDIR S_IFDIR
#define _MAX_PATH PATH_MAX
#define MKDIR(A) mkdir((A), 0777)
Functions
int _kbhit ()
bool keyBoardHit ()
static int MkDir (const char *dir)
int upc::getCols (istream &is, vstring &cols)
bool upc::keyStroke (char key=0)
FileInfo upc::fileInfo (const Path &fname)
static int _MkDir (const char *path)
Macro Definition Documentation
_MAX_PATH
#define _MAX_PATH PATH_MAX
Definition at line 148 of file filename.cpp.
_S_IFDIR
#define _S_IFDIR S_IFDIR
Definition at line 147 of file filename.cpp.
_stati64
#define _stati64 stat
Definition at line 146 of file filename.cpp.
MKDIR
#define MKDIR (A) mkdir((A), 0777)
Definition at line 149 of file filename.cpp.
Function Documentation
_kbhit()
int _kbhit ()
Definition at line 24 of file filename.cpp.
Referenced by keyBoardHit().
_MkDir()
static int _MkDir (const char * path) static
Definition at line 213 of file filename.cpp.
References MKDIR.
Referenced by MkDir().
keyBoardHit()
bool keyBoardHit () inline
Definition at line 77 of file filename.cpp.
References _kbhit().
Referenced by upc::keyStroke().
MkDir()
static int MkDir (const char * dir) static
Definition at line 222 of file filename.cpp.
References _MAX_PATH, and _MkDir().
Referenced by upc::Directory::make().