Pr치ctica 3 de PAV - detecci칩n de pitch: /Users/davidbonet/Desktop/p3-pso/src/get_pitch/pitch_evaluate.cpp File Reference
pitch_evaluate.cpp File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <vector>
#include <math.h>
#include <stdlib.h>
#include "docopt.h"
Functions
int read_vector (const string &filename, vector< float > &x)
void compare (const vector< float > &vref, const vector< float > &vtest, int &num_voiced, int &num_unvoiced, int &num_voiced_unvoiced, int &num_unvoiced_voiced, int &num_voiced_voiced, int &num_gross_errors, float &fine_error)
void print_results (int nframes, int num_voiced, int num_unvoiced, int num_voiced_unvoiced, int num_unvoiced_voiced, int num_voiced_voiced, int num_gross_errors, float fine_errori, string filename)
int main (int argc, const char *argv[])
Variables
const float gross_threshold = 0.2F
static const char USAGE []
Function Documentation
compare()
void compare (const vector< float > & vref, const vector< float > & vtest, int & num_voiced, int & num_unvoiced, int & num_voiced_unvoiced, int & num_unvoiced_voiced, int & num_voiced_voiced, int & num_gross_errors, float & fine_error)
Definition at line 129 of file pitch_evaluate.cpp.
References gross_threshold.
Referenced by main().
main()
int main (int argc, const char * argv[])
Definition at line 40 of file pitch_evaluate.cpp.
References run_tests::args, compare(), docopt::docopt(), print_results(), read_vector(), and USAGE.
print_results()
void print_results (int nframes, int num_voiced, int num_unvoiced, int num_voiced_unvoiced, int num_unvoiced_voiced, int num_voiced_voiced, int num_gross_errors, float fine_errori, string filename)
cout << fixed << setprecision(2); cout << "\n===>\t" << filename << ":\t" << 100 * score << " %\n";
Definition at line 170 of file pitch_evaluate.cpp.
References gross_threshold.
Referenced by main().
read_vector()
int read_vector (const string & filename, vector< float > & x)
Definition at line 116 of file pitch_evaluate.cpp.
Referenced by main().
Variable Documentation
gross_threshold
const float gross_threshold = 0.2F
Definition at line 24 of file pitch_evaluate.cpp.
Referenced by compare(), and print_results().
USAGE
const char USAGE[] static
Initial value:
= R"(
pitch_evaluate - Evaluate error rate of pitch evaluation
Usage:
    pitch_evaluate <file-f0ref> ...
Arguments:
    file-f0ref  File with the reference values of F0 (ext. .f0ref)
Note:
    For each reference file, a test file is required in the same directory
    with the same base name and with extension .f0
)"
Definition at line 26 of file pitch_evaluate.cpp.
Referenced by main().