Pr치ctica 3 de PAV - detecci칩n de pitch: /Users/davidbonet/Desktop/p3-pso/src/test_fft/test_fft.cpp File Reference
test_fft.cpp File Reference
#include <iostream>
#include <cmath>
#include <ffft/FFTReal.h>
Macros
#define N 32
Functions
int main ()
Macro Definition Documentation
N
#define N 32
Definition at line 6 of file test_fft.cpp.
Function Documentation
main()
int main ()
Definition at line 10 of file test_fft.cpp.
References ffft::FFTReal< DT >::do_fft(), ffft::FFTReal< DT >::do_ifft(), N, and ffft::FFTReal< DT >::rescale().